services:
  - type: web
    plan: static
    name: parallel-histories
    buildCommand: npm install && npm run build
    staticPublishPath: out
    envVars:
      - key: NODE_VERSION
        value: "20"
